######################## default configuration ####################
baseURL = "http://example.org/"
languageCode = "de-DE"
title = "La Volotte"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  link = "css/custom.css"
  [[params.plugins.css]]
  link = "plugins/lightbox/lightbox.min.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  link = "js/custom.js"
  [[params.plugins.js]]
  link = "js/script.js"
  [[params.plugins.js]]
  link = "plugins/lightbox/lightbox.min.js"
  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Produkte"
  URL = "products"
  weight = 1
  
  #[[menu.main]]
  #name = "Blog"
  #URL = "blog"
  #weight = 2
  
  [[menu.main]]
  name = "Aktuelles"
  URL = "aktuelles"
  weight = 3

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 4
  
  [[menu.main]]
  name = "Kontakt"
  URL = "contact"
  weight = 5


  ############# Brands menu #############
  [[menu.brands]]
  name = "Alle"
  URL = "products"
  weight = 1
  
  [[menu.brands]]
  name = "Atelier Zitron"
  URL = "/categories/atelier-zitron/"
  weight = 2
  
  [[menu.brands]]
  name = "BC-Garn"
  URL = "/categories/bc-garn/"
  weight = 3
  
  [[menu.brands]]
  name = "Isager"
  URL = "/categories/isager/"
  weight = 4
  
  [[menu.brands]]
  name = "Manos del Uruguay"
  URL = "/categories/manos-del-uruguay/"
  weight = 5

  [[menu.brands]]
  name = "Midara"
  URL = "/categories/midara/"
  weight = 6

  [[menu.brands]]
  name = "Mondial"
  URL = "/categories/mondial/"
  weight = 7

  [[menu.brands]]
  name = "Schoppel"
  URL = "/categories/schoppel/"
  weight = 8

  [[menu.brands]]
  name = "Seehawer & Siebert-Naturfasern"
  URL = "/categories/seehawer-siebert-naturfasern/"
  weight = 9

  [[menu.brands]]
  name = "The Fibre Company"
  URL = "/categories/the-fibre-company/"
  weight = 10

  [[menu.brands]]
  name = "Franziska Uhl"
  URL = "/categories/franziska-uhl/"
  weight = 11

  [[menu.brands]]
  name = "Erika Knight"
  URL = "/categories/erika-knight/"
  weight = 12

  ############# Materials menu #############
  [[menu.materials]]
  name = "Alle"
  URL = "products"
  weight = 1
  
  [[menu.materials]]
  name = "Polyamid"
  URL = "/tags/polyamid/"
  weight = 2
  
  [[menu.materials]]
  name = "Alpaka"
  URL = "/tags/alpaka/"
  weight = 4

  [[menu.materials]]
  name = "Bambus"
  URL = "/tags/bambus/"
  weight = 5

  [[menu.materials]]
  name = "Baumwolle"
  URL = "/tags/baumwolle/"
  weight = 6

  [[menu.materials]]
  name = "Bouretteseide"
  URL = "/tags/bouretteseide/"
  weight = 8

  [[menu.materials]]
  name = "Cashmere"
  URL = "/tags/cashmere/"
  weight = 9

  [[menu.materials]]
  name = "Hanf"
  URL = "/tags/hanf/"
  weight = 10

  [[menu.materials]]
  name = "Leinen"
  URL = "/tags/leinen/"
  weight = 12

  [[menu.materials]]
  name = "Maulbeerseide"
  URL = "/tags/Maulbeerseide/"
  weight = 14

  [[menu.materials]]
  name = "Schurwolle (GOTS)"
  URL = "/tags/schurwolle-GOTS/"
  weight = 15

  [[menu.materials]]
  name = "Mohair"
  URL = "/tags/mohair/"
  weight = 16

  [[menu.materials]]
  name = "Baumwolle, ökologisch"
  URL = "/tags/baumwolle-oeko/"
  weight = 17

  [[menu.materials]]
  name = "Ramie"
  URL = "/tags/ramie/"
  weight = 18

  [[menu.materials]]
  name = "Baumwolle (Recycling)"
  URL = "/tags/baumwolle-recycling/"
  weight = 19

  [[menu.materials]]
  name = "Schurwolle"
  URL = "/tags/schurwolle/"
  weight = 20

  [[menu.materials]]
  name = "Seide"
  URL = "/tags/seide/"
  weight = 21

  [[menu.materials]]
  name = "Tencel"
  URL = "/tags/tencel/"
  weight = 22

  [[menu.materials]]
  name = "Tussahseide"
  URL = "/tags/tussahseide/"
  weight = 23

  [[menu.materials]]
  name = "Viscose"
  URL = "/tags/viscose/"
  weight = 24
  
  [[menu.materials]]
  name = "Yak"
  URL = "/tags/yak/"
  weight = 25

  [[menu.materials]]
  name = "Baumwolle (GOTS)"
  URL = "/tags/baumwolle-GOTS/"
  weight = 25

  [[menu.materials]]
  name = "Baumwolle(KbA)"
  URL = "/tags/baumwolle-KbA/"
  weight = 25
 

  ############# Nadelstaerke menu #############
  [[menu.nadels]]
  name = "Alle"
  URL = "products"
  weight = 1
  
  [[menu.nadels]]
  name = "1,5-2,5"
  URL = "/tags/1.5-2.5/"
  weight = 2

  [[menu.nadels]]
  name = "2,5-3,5"
  URL = "/tags/2.5-3.5/"
  weight = 3

  [[menu.nadels]]
  name = "2,0-3,0"
  URL = "/tags/2.0-3.0/"
  weight = 4

  [[menu.nadels]]
  name = "2,0-3,5"
  URL = "/tags/2.0-3.5/"
  weight = 5

  [[menu.nadels]]
  name = "2,0-4,5"
  URL = "/tags/2.0-4.5/"
  weight = 6
  
  [[menu.nadels]]
  name = "2,25-3,5"
  URL = "/tags/2.25-3.5/"
  weight = 7

  [[menu.nadels]]
  name = "2,5-3,0"
  URL = "/tags/2.5-3.0/"
  weight = 8

  [[menu.nadels]]
  name = "2,5-3,5"
  URL = "/tags/2.5-3.5/"
  weight = 9

  [[menu.nadels]]
  name = "3,0"
  URL = "/tags/3.0/"
  weight = 10

  [[menu.nadels]]
  name = "3,0-3,5"
  URL = "/tags/3.0-3.5/"
  weight = 11

  [[menu.nadels]]
  name = "3,0-4,0"
  URL = "/tags/3.0-4.0/"
  weight = 12

  [[menu.nadels]]
  name = "3,5-4,0"
  URL = "/tags/3.5-4.0/"
  weight = 13

  [[menu.nadels]]
  name = "3,75-4,0"
  URL = "/tags/3.75-4.0/"
  weight = 14

  [[menu.nadels]]
  name = "4,0-4,5"
  URL = "/tags/4.0-4.5/"
  weight = 15

  [[menu.nadels]]
  name = "4,0-5,0"
  URL = "/tags/4.0-5.0/"
  weight = 16

  [[menu.nadels]]
  name = "4,0-5,5"
  URL = "/tags/4.0-5.5/"
  weight = 17

  [[menu.nadels]]
  name = "4,0-6,0"
  URL = "/tags/4.0-6.0/"
  weight = 18

  [[menu.nadels]]
  name = "4,5-5,0"
  URL = "/tags/4.5-5.0/"
  weight = 19

  [[menu.nadels]]
  name = "5,0-5,5"
  URL = "/tags/5.0-5.5/"
  weight = 20

  [[menu.nadels]]
  name = "5,0-6,0"
  URL = "/tags/5.0-6.0/"
  weight = 21

  [[menu.nadels]]
  name = "5,0-7,0"
  URL = "/tags/5.0-7.0/"
  weight = 22

  [[menu.nadels]]
  name = "6,0-7,0"
  URL = "/tags/6.0-7.0/"
  weight = 23

  [[menu.nadels]]
  name = "8,0-9,0"
  URL = "/tags/8.0-9.0/"
  weight = 24

  [[menu.nadels]]
  name = "15,0"
  URL = "/tags/15.0/"
  weight = 24
  


  ############# footer menu #############
  [[menu.footer]]
  name = "Produkte"
  URL = "products"
  weight = 1
  
  #[[menu.footer]]
  #name = "Blog"
  #URL = "blog"
  #weight = 2
  
  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 2

  [[menu.main]]
  name = "Aktuelles"
  URL = "aktuelles"
  weight = 3
  
  [[menu.footer]]
  name = "Impressum"
  URL = "impressum"
  weight = 4

  [[menu.footer]]
  name = "Datenschutz"
  URL = "datenschutz"
  weight = 5

  [[menu.footer]]
  name = "AGB"
  URL = "agb"
  weight = 6

  [[menu.footer]]
  name = "Widerrufsrecht "
  URL = "widerrufsrecht"
  weight = 7
  
  [[menu.footer]]
  name = "Versandbedingungen"
  URL = "versand"
  weight = 8

  [[menu.footer]]
  name = "Kontakt"
  URL = "contact"
  weight = 9


#################### default parameters ################################
[params]
logo = "images/lavolottelogo.png"
home = "Home"
# Meta data
description = "Die bezaubernde, alte Ladentür öffnet sich zu ‘La Volotte’ ,und ein charmantes, kleines Geschäft mit einer großen Auswahl an ausgesuchten, hochwertigen Naturgarnen aus verschiedenen Ländern lädt die Kundschaft zum Schwelgen und Finden ein!"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "50.7716545"
mapLongitude = "6.0767233"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "+49 (0)241 47587794"
email = "wolle@la-volotte.de"
location = "Jakobstrasse 107,  "
location1 = "D-52064 Aachen"
# copyright
copyright = "| La Volotte 2020 © |"


  # Preloader
  [params.preloader]
  enable = false
  preloader = "/images/giphy.gif" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/Lavolotte"
  
  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/la_volotte_wollladen/"
  
  [[params.social]]
  icon = "ti-pinterest"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io

[taxonomies]
  category = "categories"
  tag = "tags"
  brand = "brands"
  nadel = "nadels"
  
